
extensions:
  healthcheckv2:
    use_v2: true
    http:


  jaeger_storage:
    backends:
      some_storage:
        elasticsearch:
          server_urls:
            - http://elasticsearch:9200
          indices:
            index_prefix: "jaeger-main"
            spans:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            services:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            dependencies:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            sampling:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
      another_storage:
        elasticsearch:
          server_urls:
            - http://elasticsearch:9200
          indices:
            index_prefix: "jaeger-archive"


  jaeger_query:
    storage:
      traces: some_storage
      traces_archive: another_storage
    ui:
      config_file: ./cmd/jaeger/config-ui.json


receivers:
  otlp:
    protocols:
      # grpc:
      #  endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"


processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage



service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger_as_all_in_one
    metrics:
      level: detailed
      address: 0.0.0.0:8888
    logs:
      level: debug
