services:
  order-service:
    build:
      context: ../order-service/.
      dockerfile: ../order-service/Dockerfile
    ports:
        - "8000:8000"
    environment:
      - APP_ENV=stage
    depends_on:
      - otel-collector

  inventory-service:
    build:
      context: ../inventory-service/.
      dockerfile: ../inventory-service/Dockerfile
    ports:
        - "8010:8010"
    environment:
      - APP_ENV=stage
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.119.0
    ports:
      - "4317:4317"   # otel gRPC receiver for traces, log, and metrics
      # - "4318:4318"   # otel HTTP receiver for traces, log, and metrics
      # - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "1888:1888" # pprof extension
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
    volumes:
      - ./config_volumes/otel-config.yaml:/etc/otel-config.yaml
    command: ["--config", "/etc/otel-config.yaml"]
    depends_on:
     clickhouse:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:24.12-alpine
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
        - CLICKHOUSE_USER=default
        - CLICKHOUSE_PASSWORD=password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - "./data_volumes/clickhouse/database/:/var/lib/clickhouse/"
      - "./data_volumes/clickhouse/log/:/var/log/clickhouse-server/"
    healthcheck:
      test: ["CMD-SHELL", "clickhouse client --query='SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 2
      # start_period can be longer if your MinIO or other dependencies need more time
      start_period: 30s

  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3000:3000"
    volumes:
      - ./data_volumes/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning