apiVersion: 1

datasources:
  # Configure prometheus as data source for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  # Configure Loki as data source for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true

  # Configure Jaeger as data source for traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-all:16686
    jsonData:
      tracesToLogs:
        datasourceUid: "Loki"
        tags: ["instance", "job"]
        mappedTags: [{ key: "service.name", value: "service" }]
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
    editable: true
